name: Deploy Server

on: 
  push: 
    branches: 
      - master
    paths: 
      - "src/*"
      - ".github/workflows/DeployServer.yml"

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: test
        run: echo "hi from github workflow"
      - name: get repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: test
        run: echo "hi from github workflow"
      - name: add github username
        run: git config --global user.name "youngmansumit"
      - name: add github email
        run: git config --global user.email "svsumitvishwakarma@gmail.com"
      - name: add heroku remote
        run: git remote add heroku https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/${{secrets.HEROKU_APP_NAME}}.git
      - name: push to heroku
        run: git push heroku master --force